INSERT INTO `noUse` (`sname`) VALUES ('(It Goes Like) Nanana (Edit)');
INSERT INTO `noUse` (`sname`) VALUES ('All Night');
INSERT INTO `noUse` (`sname`) VALUES ('Allergy');
INSERT INTO `noUse` (`sname`) VALUES ('Baby, Don\'t Cry (人鱼的眼泪)');
INSERT INTO `noUse` (`sname`) VALUES ('Cheri Cheri Lady');
INSERT INTO `noUse` (`sname`) VALUES ('Cruel Summer');
INSERT INTO `noUse` (`sname`) VALUES ('Cupid');
INSERT INTO `noUse` (`sname`) VALUES ('Cupid (Twin Ver.)');
INSERT INTO `noUse` (`sname`) VALUES ('Cupid – Twin Ver. (FIFTY FIFTY) – Sped Up Version');
INSERT INTO `noUse` (`sname`) VALUES ('C级浪漫');
INSERT INTO `noUse` (`sname`) VALUES ('Da Capo');
INSERT INTO `noUse` (`sname`) VALUES ('Daisuki');
INSERT INTO `noUse` (`sname`) VALUES ('Dancing is Healing');
INSERT INTO `noUse` (`sname`) VALUES ('Fly, My Wings');
INSERT INTO `noUse` (`sname`) VALUES ('Giving Me');
INSERT INTO `noUse` (`sname`) VALUES ('Good Love');
INSERT INTO `noUse` (`sname`) VALUES ('I\'ll Do It (Sped Up Version)');
INSERT INTO `noUse` (`sname`) VALUES ('Idol');
INSERT INTO `noUse` (`sname`) VALUES ('insomnia');
INSERT INTO `noUse` (`sname`) VALUES ('Letting Go');
INSERT INTO `noUse` (`sname`) VALUES ('Miracle');
INSERT INTO `noUse` (`sname`) VALUES ('My Light');
INSERT INTO `noUse` (`sname`) VALUES ('P.Y.T');
INSERT INTO `noUse` (`sname`) VALUES ('Pakistan');
INSERT INTO `noUse` (`sname`) VALUES ('RELAX(睿猎)');
INSERT INTO `noUse` (`sname`) VALUES ('Reverse');
INSERT INTO `noUse` (`sname`) VALUES ('Say It Right');
INSERT INTO `noUse` (`sname`) VALUES ('Sea Of Problems');
INSERT INTO `noUse` (`sname`) VALUES ('Spicy');
INSERT INTO `noUse` (`sname`) VALUES ('Sprinter');
INSERT INTO `noUse` (`sname`) VALUES ('Strangers');
INSERT INTO `noUse` (`sname`) VALUES ('Time Stop');
INSERT INTO `noUse` (`sname`) VALUES ('Tropical Resolve');
INSERT INTO `noUse` (`sname`) VALUES ('vampire');
INSERT INTO `noUse` (`sname`) VALUES ('Who Told You');
INSERT INTO `noUse` (`sname`) VALUES ('WHOOSISHYT');
INSERT INTO `noUse` (`sname`) VALUES ('[Drill] Central Cee Type Drill Beat \'\'Lemonade\'\'');
INSERT INTO `noUse` (`sname`) VALUES ('[Drill] Central Cee Type Drill Beat \'\'Somebody\'\'');
INSERT INTO `noUse` (`sname`) VALUES ('なんでもないや（没什么大不了）');
INSERT INTO `noUse` (`sname`) VALUES ('アイドル');
INSERT INTO `noUse` (`sname`) VALUES ('メフィスト');
INSERT INTO `noUse` (`sname`) VALUES ('一般的一天 (LIVE版)');
INSERT INTO `noUse` (`sname`) VALUES ('不爱就算（whatever）');
INSERT INTO `noUse` (`sname`) VALUES ('予你');
INSERT INTO `noUse` (`sname`) VALUES ('五号咖啡馆');
INSERT INTO `noUse` (`sname`) VALUES ('会魔法的老人 (LIVE版)');
INSERT INTO `noUse` (`sname`) VALUES ('你');
INSERT INTO `noUse` (`sname`) VALUES ('全世界会唱的歌');
INSERT INTO `noUse` (`sname`) VALUES ('凄美地');
INSERT INTO `noUse` (`sname`) VALUES ('变成星星飞走了');
INSERT INTO `noUse` (`sname`) VALUES ('向云端');
INSERT INTO `noUse` (`sname`) VALUES ('唯一');
INSERT INTO `noUse` (`sname`) VALUES ('多远都要在一起');
INSERT INTO `noUse` (`sname`) VALUES ('天外来物');
INSERT INTO `noUse` (`sname`) VALUES ('天天');
INSERT INTO `noUse` (`sname`) VALUES ('天若有情');
INSERT INTO `noUse` (`sname`) VALUES ('如果呢');
INSERT INTO `noUse` (`sname`) VALUES ('嫁东风');
INSERT INTO `noUse` (`sname`) VALUES ('就让这大雨全都落下');
INSERT INTO `noUse` (`sname`) VALUES ('带我去找夜生活');
INSERT INTO `noUse` (`sname`) VALUES ('开往早晨的午夜');
INSERT INTO `noUse` (`sname`) VALUES ('心');
INSERT INTO `noUse` (`sname`) VALUES ('想想就烦');
INSERT INTO `noUse` (`sname`) VALUES ('我不曾忘记');
INSERT INTO `noUse` (`sname`) VALUES ('我想念 (Live版)');
INSERT INTO `noUse` (`sname`) VALUES ('我记得');
INSERT INTO `noUse` (`sname`) VALUES ('把回忆拼好给你');
INSERT INTO `noUse` (`sname`) VALUES ('时空观影券');
INSERT INTO `noUse` (`sname`) VALUES ('普通人生');
INSERT INTO `noUse` (`sname`) VALUES ('月を見ていた');
INSERT INTO `noUse` (`sname`) VALUES ('永恒的烟火');
INSERT INTO `noUse` (`sname`) VALUES ('漂');
INSERT INTO `noUse` (`sname`) VALUES ('爱人错过');
INSERT INTO `noUse` (`sname`) VALUES ('爱情转移·2023');
INSERT INTO `noUse` (`sname`) VALUES ('爱的回归线 (Live版)');
INSERT INTO `noUse` (`sname`) VALUES ('用情 (Live版)');
INSERT INTO `noUse` (`sname`) VALUES ('直到清晨黄昏（sample this）');
INSERT INTO `noUse` (`sname`) VALUES ('笼');
INSERT INTO `noUse` (`sname`) VALUES ('算了');
INSERT INTO `noUse` (`sname`) VALUES ('絆ノ奇跡');
INSERT INTO `noUse` (`sname`) VALUES ('罗生门（Follow）');
INSERT INTO `noUse` (`sname`) VALUES ('翠花');
INSERT INTO `noUse` (`sname`) VALUES ('苏珊');
INSERT INTO `noUse` (`sname`) VALUES ('诀爱·尽 (LIVE版)');
INSERT INTO `noUse` (`sname`) VALUES ('请别再给我那些答非所问');
INSERT INTO `noUse` (`sname`) VALUES ('远别');
INSERT INTO `noUse` (`sname`) VALUES ('门');
INSERT INTO `noUse` (`sname`) VALUES ('雨爱 (Live版)');
INSERT INTO `noUse` (`sname`) VALUES ('风驶过的声音是');
INSERT INTO `noUse` (`sname`) VALUES ('꽃(FLOWER)');
INSERT INTO `noUse` (`sname`) VALUES ('퀸카 (Queencard)');
