INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('1024308', '张碧晨', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 2 @#$#@ 4 @#$#@ 4 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('1038123', 'Brooklyn Duo', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 0 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('1132392', '马思唯', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 2 @#$#@ 6 @#$#@ 2 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('1143033', '队长', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 6 @#$#@ 4 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('1155045', 'J Hus', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 3 @#$#@ 5 @#$#@ 1 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('1192268', '小霞', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 2 @#$#@ 6 @#$#@ 2 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('12001060', 'Vinida (万妮达)', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 3 @#$#@ 5 @#$#@ 2 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('12061233', 'JISOO', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 6 @#$#@ 4 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('12085424', 'Prodby玉', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 3 @#$#@ 6 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('12085585', '辛巴', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 2 @#$#@ 6 @#$#@ 2 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('1211046', 'GAI周延', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 2 @#$#@ 8 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('12132544', 'Olivia Rodrigo', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 2 @#$#@ 8 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('12156137', '太一', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 1 @#$#@ 5 @#$#@ 4 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('12175193', 'Dave', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 4 @#$#@ 6 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('12292307', '陈近南', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 4 @#$#@ 5 @#$#@ 1 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('12333145', 'DP龙猪', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 4 @#$#@ 4 @#$#@ 2 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('12487174', 'HOYO-MiX', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 1 @#$#@ 7 @#$#@ 2 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('12498122', '9COLOR', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 2 @#$#@ 0 @#$#@ 1 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('12541250', 'Arthur Rubinstein', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 0 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('12570417', '那奇沃夫', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 1 @#$#@ 6 @#$#@ 3 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('12605500', '盛宇D-SHINE', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 3 @#$#@ 7 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('12660032', 'Hannah Laing', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 1 @#$#@ 0 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('12676697', '告五人', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 3 @#$#@ 7 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('12875936', '康熙', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 5 @#$#@ 5 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('12967449', 'TangoZ', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 1 @#$#@ 7 @#$#@ 2 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('13059642', 'Peggy Gou', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 2 @#$#@ 4 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('13112601', 'Wiz_H张子豪', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 3 @#$#@ 4 @#$#@ 2 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('13145341', 'YO16', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 1 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('13159084', 'Max Oazo', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 5 @#$#@ 4 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('13391917', 'D-Block Europe', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 2 @#$#@ 7 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('14047792', 'Kassia', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 0 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('14055085', '(G)I-DLE', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 6 @#$#@ 4 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('14312549', '王贰浪', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 4 @#$#@ 5 @#$#@ 1');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('14885023', '花玲', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 1 @#$#@ 6 @#$#@ 3 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('15290', '澤野弘之', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 1 @#$#@ 5 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('159300', '米津玄師', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 5 @#$#@ 5 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('20574', 'MAN WITH A MISSION', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 1 @#$#@ 6 @#$#@ 3 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('22492', '女王蜂', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 1 @#$#@ 6 @#$#@ 3 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('28178623', 'Zelimir Panic', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 0 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('28201180', 'Noble Music Project', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 0 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('2843', '郭顶', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 1 @#$#@ 7 @#$#@ 2 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('28642672', 'kkluv', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 2 @#$#@ 8 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('29051613', '郑润泽', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 2 @#$#@ 8 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('29235968', 'PEKIDS', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 3 @#$#@ 0 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('29588305', '刘大拿', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 3 @#$#@ 7 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('29802127', '单依纯', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 4 @#$#@ 6 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('29968', 'Calvin Harris', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 2 @#$#@ 8 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('30436301', 'Adoreya', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 2 @#$#@ 2 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('30959203', '江意间', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 3 @#$#@ 5 @#$#@ 2 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('31309410', 'XMASwu(吴骜)', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 1 @#$#@ 3 @#$#@ 6 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('31915294', 'BlackDD', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 0 @#$#@ 1 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('32829438', 'CHAjii', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 0 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('32887341', 'Frank Young', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 0 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('33216986', 'SETI', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 3 @#$#@ 7 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('33259235', '梨冻紧', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 4 @#$#@ 4 @#$#@ 1');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('33850', 'Glenn Gould', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 0 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('33927412', 'YOASOBI', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 5 @#$#@ 5 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('339594', 'Mili', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 5 @#$#@ 3 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('34055135', 'Spylent', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 1 @#$#@ 5 @#$#@ 4 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('36985903', '海洋Bo', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 1 @#$#@ 4 @#$#@ 5 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('37351063', 'aespa', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 7 @#$#@ 3 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('42870', 'Rudimental', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 7 @#$#@ 2 @#$#@ 1 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('44266', 'Taylor Swift', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 4 @#$#@ 6 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('46590948', 'l19u1d', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 0 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('47057337', '李小眼', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 4 @#$#@ 3 @#$#@ 3 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('47264102', 'NUEKI', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 0 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('47914577', '纳兰慧心', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 0 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('48214256', 'Jazzy', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 3 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('48577041', 'Mikey-18', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 1 @#$#@ 5 @#$#@ 4 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('49246882', 'BeMax', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 2 @#$#@ 5 @#$#@ 1 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('49287726', 'Neil.', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 1 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('50532654', 'Martin Carlos', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 4 @#$#@ 6 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('50561551', 'Hana0nna', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 1 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('51455310', 'dori', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 8 @#$#@ 2 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('51957057', 'ljz329', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 2 @#$#@ 6 @#$#@ 1 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('5196', '陶喆', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 2 @#$#@ 5 @#$#@ 3 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('52637913', 'Tiko', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 4 @#$#@ 1 @#$#@ 2 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('53477009', '16', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 3 @#$#@ 7 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('54131214', 'Prog Monster', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 1 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('54746300', 'FIFTY FIFTY', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '1 @#$#@ 7 @#$#@ 2 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('5538', '汪苏泷', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 3 @#$#@ 5 @#$#@ 2 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('55851238', 'Glichery', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 1 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('56000828', 'Juudy', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 2 @#$#@ 0 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('56326185', 'sped up 8282', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 2 @#$#@ 1 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('56742', 'Elise Lieberth', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 1 @#$#@ 2 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('5781', '薛之谦', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 1 @#$#@ 5 @#$#@ 3 @#$#@ 1');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('60228', 'Heidi Montag', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 3 @#$#@ 7 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('6731', '赵雷', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 2 @#$#@ 7 @#$#@ 1');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('7063', '黄丽玲', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 0 @#$#@ 1 @#$#@ 9 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('7214', '蔡健雅', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 1 @#$#@ 4 @#$#@ 5 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('759509', 'EXO', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 6 @#$#@ 3 @#$#@ 1 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('7763', 'G.E.M.邓紫棋', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 8 @#$#@ 2 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('865007', '法老', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 1 @#$#@ 9 @#$#@ 0 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('893259', '金玟岐', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 1 @#$#@ 1 @#$#@ 7 @#$#@ 1');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('9269', '容祖儿', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 1 @#$#@ 6 @#$#@ 3 @#$#@ 0');
INSERT INTO `singerEmo` (`seid`, `sename`, `emo`, `num`) VALUES ('9808', '王胜娚', '积极 @#$#@ 稍积极 @#$#@ 中性 @#$#@ 稍消极 @#$#@ 消极', '0 @#$#@ 2 @#$#@ 6 @#$#@ 2 @#$#@ 0');
