INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('(G)I-DLE', 'down', 30);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('(G)I-DLE', 'it', 23);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('(G)I-DLE', 'la', 48);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('(G)I-DLE', 'love', 42);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('(G)I-DLE', 'me', 49);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('(G)I-DLE', 'night', 36);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('(G)I-DLE', 'the', 48);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('(G)I-DLE', 'to', 28);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('(G)I-DLE', 'we', 34);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('(G)I-DLE', 'you', 49);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('16', 'all', 32);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('16', 'Coiling', 30);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('16', 'it', 48);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('16', 'love', 24);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('16', 'me', 25);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('16', 'my', 51);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('16', 'the', 35);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('16', 'to', 32);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('16', 'you', 54);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Adoreya', '----------------------------------------', 5);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Adoreya', 'Darling', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Adoreya', '不行', 3);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Adoreya', '世界', 2);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Adoreya', '咲太', 5);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Adoreya', '好好', 2);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Adoreya', '尚文', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Adoreya', '没事', 4);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Adoreya', '消失', 2);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Adoreya', '驾驶', 5);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('aespa', 'it', 45);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('aespa', 'la', 47);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('aespa', 'Ma', 30);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('aespa', 'me', 67);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('aespa', 'on', 33);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('aespa', 'to', 30);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('aespa', 'ya', 33);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('aespa', 'You', 30);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('aespa', 'Zu', 84);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('BeMax', 'Cherkassky', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('BeMax', 'in', 14);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('BeMax', 'love', 23);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('BeMax', 'me', 19);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('BeMax', 'on', 15);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('BeMax', 'the', 17);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('BeMax', 'twisted', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('BeMax', 'you', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('BlackDD', '万重山', 1);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('BlackDD', '已过', 1);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('BlackDD', '轻舟', 1);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Calvin Harris', 'in', 65);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Calvin Harris', 'it', 78);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Calvin Harris', 'like', 35);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Calvin Harris', 'me', 64);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Calvin Harris', 'my', 38);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Calvin Harris', 'oh', 72);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Calvin Harris', 'on', 82);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Calvin Harris', 'the', 96);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Calvin Harris', 'to', 38);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Calvin Harris', 'you', 140);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('D-Block Europe', 'and', 51);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('D-Block Europe', 'in', 101);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('D-Block Europe', 'it', 85);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('D-Block Europe', 'my', 106);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('D-Block Europe', 'on', 72);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('D-Block Europe', 'that', 87);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('D-Block Europe', 'the', 211);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('D-Block Europe', 'to', 52);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('D-Block Europe', 'up', 45);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('D-Block Europe', 'you', 113);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Dave', 'and', 104);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Dave', 'in', 116);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Dave', 'it', 93);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Dave', 'my', 121);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Dave', 'on', 97);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Dave', 'one', 87);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Dave', 'that', 82);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Dave', 'the', 216);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Dave', 'to', 86);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Dave', 'you', 90);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('dori', 'all', 52);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('dori', 'give', 40);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('dori', 'gonna', 26);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('dori', 'in', 25);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('dori', 'it', 44);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('dori', 'love', 50);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('dori', 'my', 90);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('dori', 'You', 58);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('dori', 'your', 26);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('DP龙猪', 'Baby', 20);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('DP龙猪', 'it', 13);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('DP龙猪', 'know', 73);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('DP龙猪', 'me', 14);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('DP龙猪', 'you', 11);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('DP龙猪', 'your', 13);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('DP龙猪', '下雨天', 11);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('DP龙猪', '今晚', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('DP龙猪', '环球小姐', 23);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('DP龙猪', '讨厌', 21);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Elise Lieberth', 'all', 15);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Elise Lieberth', 'and', 14);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Elise Lieberth', 'be', 20);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Elise Lieberth', 'can', 20);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Elise Lieberth', 'don', 17);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Elise Lieberth', 'is', 15);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Elise Lieberth', 'me', 31);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Elise Lieberth', 'mean', 24);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Elise Lieberth', 'to', 31);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Elise Lieberth', 'you', 63);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('EXO', 'Baby', 31);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('EXO', 'Call', 33);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('EXO', 'Cry', 41);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('EXO', 'Don', 32);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('EXO', 'Eu', 36);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('EXO', 'me', 33);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('EXO', 'oh', 31);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('EXO', 'Reong', 36);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('EXO', 'Reu', 36);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('FIFTY FIFTY', 'ah', 60);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('FIFTY FIFTY', 'Cupid', 36);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('FIFTY FIFTY', 'da', 44);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('FIFTY FIFTY', 'in', 53);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('FIFTY FIFTY', 'it', 60);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('FIFTY FIFTY', 'like', 39);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('FIFTY FIFTY', 'log', 36);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('FIFTY FIFTY', 'me', 122);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('FIFTY FIFTY', 'that', 36);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('FIFTY FIFTY', 'you', 68);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('G.E.M.邓紫棋', 'did', 27);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('G.E.M.邓紫棋', 'go', 19);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('G.E.M.邓紫棋', 'Groinig', 20);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('G.E.M.邓紫棋', 'oh', 33);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('G.E.M.邓紫棋', 'Where', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('G.E.M.邓紫棋', 'you', 20);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('G.E.M.邓紫棋', '再见', 19);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('G.E.M.邓紫棋', '温柔', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('G.E.M.邓紫棋', '颤抖', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('GAI周延', 'GAI', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('GAI周延', 'Say', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('GAI周延', 'We', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('GAI周延', '告诉', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('GAI周延', '周延', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('GAI周延', '啥子', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('GAI周延', '时间', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('GAI周延', '珍贵', 14);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('GAI周延', '西多士', 24);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('GAI周延', '面对', 13);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Glichery', 'Break', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Glichery', 'fool', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Glichery', 'hes', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Glichery', 'ping', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Glichery', 'shawty', 21);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Glichery', 'spit', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Glichery', 'that', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Glichery', 'The', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Glichery', 'tricks', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Hannah Laing', 'could', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Hannah Laing', 'Good', 31);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Hannah Laing', 'got', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Hannah Laing', 'head', 23);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Hannah Laing', 'loving', 31);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Hannah Laing', 'my', 21);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Hannah Laing', 'to', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Hannah Laing', 've', 19);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Hannah Laing', 'you', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Heidi Montag', 'be', 93);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Heidi Montag', 'do', 90);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Heidi Montag', 'it', 121);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Heidi Montag', 'like', 83);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Heidi Montag', 'll', 151);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Heidi Montag', 'me', 131);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Heidi Montag', 'that', 132);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Heidi Montag', 'what', 87);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Heidi Montag', 'you', 183);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Heidi Montag', 'your', 101);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('HOYO-MiX', 'and', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('HOYO-MiX', 'be', 15);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('HOYO-MiX', 'HOYO', 35);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('HOYO-MiX', 'it', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('HOYO-MiX', 'MiX', 34);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('HOYO-MiX', 'of', 30);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('HOYO-MiX', 'the', 77);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('HOYO-MiX', 'to', 44);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('HOYO-MiX', 'up', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('HOYO-MiX', 'will', 15);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('J Hus', 'an', 62);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('J Hus', 'in', 78);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('J Hus', 'it', 94);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('J Hus', 'like', 71);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('J Hus', 'me', 70);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('J Hus', 'my', 143);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('J Hus', 'opp', 54);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('J Hus', 'the', 154);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('J Hus', 'with', 62);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('J Hus', 'you', 116);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Jazzy', 'da', 72);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Jazzy', 'Give', 20);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Jazzy', 'giving', 34);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Jazzy', 'got', 23);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Jazzy', 'in', 29);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Jazzy', 'me', 89);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Jazzy', 're', 42);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Jazzy', 'the', 47);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Jazzy', 'you', 78);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Jazzy', 'your', 23);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('JISOO', 'go', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('JISOO', 'it', 15);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('JISOO', 'me', 28);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('JISOO', 'my', 24);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('JISOO', 'no', 30);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('JISOO', 'Oh', 30);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('JISOO', 'ooh', 29);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('JISOO', 'the', 22);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('JISOO', 'you', 49);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Juudy', 'Growth', 3);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Juudy', 'Shanghai', 3);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Juudy', 'Studio', 3);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Juudy', 'Studios', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Juudy', '倾听', 3);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Juudy', '化作', 3);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Juudy', '找寻', 3);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Juudy', '抓不住', 3);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Juudy', '离别', 3);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Juudy', '转眼', 4);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('kkluv', 'baby', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('kkluv', 'bae', 18);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('kkluv', 'en', 24);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('kkluv', 'my', 17);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('kkluv', 'she', 24);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('kkluv', 'up', 28);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('kkluv', 'you', 21);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('kkluv', '兄弟', 13);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('kkluv', '告诉', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('kkluv', '往前', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('ljz329', 'do', 73);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('ljz329', 'gotta', 17);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('ljz329', 'it', 78);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('ljz329', 'love', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('ljz329', 'make', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('ljz329', 'me', 22);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('ljz329', 'my', 22);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('ljz329', 'the', 13);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('ljz329', 'to', 20);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('ljz329', 'you', 33);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('MAN WITH A MISSION', 'and', 33);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('MAN WITH A MISSION', 'ground', 33);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('MAN WITH A MISSION', 'me', 57);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('MAN WITH A MISSION', 'my', 39);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('MAN WITH A MISSION', 'on', 52);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('MAN WITH A MISSION', 'the', 130);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('MAN WITH A MISSION', 'to', 46);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('MAN WITH A MISSION', 'we', 28);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('MAN WITH A MISSION', 'you', 35);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('MAN WITH A MISSION', 'your', 28);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Martin Carlos', 'can', 51);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Martin Carlos', 'Carlos', 41);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Martin Carlos', 'in', 33);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Martin Carlos', 'me', 86);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Martin Carlos', 'that', 45);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Martin Carlos', 'the', 43);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Martin Carlos', 'to', 39);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Martin Carlos', 'we', 42);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Martin Carlos', 'you', 105);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Max Oazo', 'can', 46);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Max Oazo', 'la', 90);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Max Oazo', 'love', 63);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Max Oazo', 'me', 68);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Max Oazo', 'my', 53);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Max Oazo', 'na', 44);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Max Oazo', 'the', 52);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Max Oazo', 'to', 38);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Max Oazo', 'up', 39);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Max Oazo', 'you', 153);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Mikey-18', 'be', 13);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Mikey-18', 'day', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Mikey-18', 'dreamlover', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Mikey-18', 'ever', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Mikey-18', 'my', 25);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Mikey-18', 'you', 15);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Mikey-18', '孤独', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Mikey-18', '情绪', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Mikey-18', '感情', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Mikey-18', '离开', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Mili', 'can', 27);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Mili', 'If', 27);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Mili', 'in', 28);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Mili', 'me', 60);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Mili', 'my', 45);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Mili', 'of', 26);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Mili', 'on', 31);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Mili', 'the', 87);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Mili', 'to', 62);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Mili', 'you', 76);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Neil.', 'be', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Neil.', 'by', 5);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Neil.', 'cord', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Neil.', 'cutting', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Neil.', 'love', 4);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Neil.', 'of', 4);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Neil.', 'our', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Neil.', 'should', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Neil.', 'the', 15);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Neil.', 'We', 14);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Olivia Rodrigo', 'and', 35);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Olivia Rodrigo', 'But', 35);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Olivia Rodrigo', 'it', 42);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Olivia Rodrigo', 'me', 69);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Olivia Rodrigo', 'so', 35);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Olivia Rodrigo', 'that', 48);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Olivia Rodrigo', 'the', 69);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Olivia Rodrigo', 'to', 40);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Olivia Rodrigo', 'you', 199);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Peggy Gou', 'do', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Peggy Gou', 'Enjoy', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Peggy Gou', 'go', 24);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Peggy Gou', 'gotta', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Peggy Gou', 'it', 30);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Peggy Gou', 'na', 153);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Peggy Gou', 'right', 18);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Peggy Gou', 'that', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Peggy Gou', 'You', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('PEKIDS', 'And', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('PEKIDS', 'can', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('PEKIDS', 'know', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('PEKIDS', 'not', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('PEKIDS', 'of', 32);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('PEKIDS', 'think', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('PEKIDS', 'wanna', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('PEKIDS', 'with', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('PEKIDS', 'You', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Prodby玉', 'bye', 24);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Prodby玉', 'check', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Prodby玉', 'ever', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Prodby玉', 'go', 15);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Prodby玉', 'it', 22);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Prodby玉', 'my', 13);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Prodby玉', 'no', 14);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Prodby玉', 'on', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Prodby玉', 'we', 14);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Prodby玉', 'yo', 14);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Prog Monster', 'and', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Prog Monster', 'Daddy', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Prog Monster', 'gave', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Prog Monster', 'he', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Prog Monster', 'it', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Prog Monster', 'like', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Prog Monster', 'right', 11);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Prog Monster', 'that', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Prog Monster', 'threw', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Prog Monster', 'to', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Rudimental', 'all', 66);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Rudimental', 'And', 40);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Rudimental', 'in', 43);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Rudimental', 'it', 111);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Rudimental', 'me', 131);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Rudimental', 'on', 76);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Rudimental', 'the', 110);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Rudimental', 'to', 47);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Rudimental', 'yeah', 67);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Rudimental', 'you', 134);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('SETI', 'Dokodemo', 20);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('SETI', 'dont', 14);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('SETI', 'Door', 27);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('SETI', 'game', 15);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('SETI', 'Music', 18);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('SETI', 'play', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('SETI', 'the', 18);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('SETI', 'why', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('SETI', 'you', 19);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('SETI', '世界', 30);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('sped up 8282', 'Baby', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('sped up 8282', 'la', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('sped up 8282', 'me', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('sped up 8282', 'need', 20);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('sped up 8282', 'now', 13);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('sped up 8282', 'that', 13);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('sped up 8282', 'the', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('sped up 8282', 'to', 13);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('sped up 8282', 'you', 31);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('sped up 8282', 'your', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Spylent', 'and', 11);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Spylent', 'Follow', 18);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Spylent', 'my', 22);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Spylent', 'on', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Spylent', 'Spylent', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Spylent', 'the', 24);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Spylent', 'wave', 15);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Spylent', '上帝', 26);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Spylent', '人类', 11);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Spylent', '橘子', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('TangoZ', 'Knock', 27);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('TangoZ', 'know', 24);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('TangoZ', 'my', 32);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('TangoZ', 'name', 20);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('TangoZ', 'out', 40);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('TangoZ', 'should', 22);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('TangoZ', 'the', 29);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('TangoZ', 'to', 20);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('TangoZ', '杭州', 20);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('TangoZ', '淘汰', 39);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Taylor Swift', 'And', 66);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Taylor Swift', 'do', 41);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Taylor Swift', 'in', 54);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Taylor Swift', 'it', 61);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Taylor Swift', 'me', 117);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Taylor Swift', 'my', 42);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Taylor Swift', 'the', 110);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Taylor Swift', 'to', 78);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Taylor Swift', 'what', 45);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Taylor Swift', 'you', 184);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Tiko', 'be', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Tiko', 'dear', 11);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Tiko', 'Everything', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Tiko', 'gang', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Tiko', 'get', 11);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Tiko', 'me', 15);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Tiko', 'My', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Tiko', 'with', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Tiko', 'you', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Tiko', '孤独', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Vinida (万妮达)', 'and', 22);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Vinida (万妮达)', 'for', 15);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Vinida (万妮达)', 'go', 14);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Vinida (万妮达)', 'know', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Vinida (万妮达)', 'me', 30);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Vinida (万妮达)', 'Production', 15);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Vinida (万妮达)', 'the', 13);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Vinida (万妮达)', 'want', 14);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Vinida (万妮达)', 'you', 51);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Vinida (万妮达)', 'Zeus', 14);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Wiz_H张子豪', 'go', 15);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Wiz_H张子豪', 'me', 21);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Wiz_H张子豪', 'tonight', 18);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Wiz_H张子豪', 'up', 14);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Wiz_H张子豪', 'wake', 14);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Wiz_H张子豪', 'you', 14);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Wiz_H张子豪', '一晚', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Wiz_H张子豪', '拦不住', 20);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Wiz_H张子豪', '滴答', 13);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('Wiz_H张子豪', '男孩', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('XMASwu(吴骜)', 'am', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('XMASwu(吴骜)', 'baby', 17);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('XMASwu(吴骜)', 'falling', 15);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('XMASwu(吴骜)', 'for', 17);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('XMASwu(吴骜)', 'in', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('XMASwu(吴骜)', 'love', 19);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('XMASwu(吴骜)', 'my', 37);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('XMASwu(吴骜)', 'round', 14);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('XMASwu(吴骜)', 'wanna', 13);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('XMASwu(吴骜)', 'you', 72);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('YOASOBI', 'it', 15);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('YOASOBI', 'love', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('YOASOBI', 'my', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('YOASOBI', 'you', 26);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('YOASOBI', '世界', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('YOASOBI', '二人', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('YOASOBI', '今日', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('YOASOBI', '何回', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('YOASOBI', '本当', 11);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('YOASOBI', '言葉', 11);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('刘大拿', 'DA', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('刘大拿', 'DI', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('刘大拿', 'go', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('刘大拿', 'you', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('刘大拿', '不在乎', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('刘大拿', '只在乎', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('刘大拿', '回忆', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('刘大拿', '朋友', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('刘大拿', '爱情', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('刘大拿', '爱过', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('单依纯', 'NEWBAND', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('单依纯', '几多', 5);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('单依纯', '发亮', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('单依纯', '台前', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('单依纯', '尊严', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('单依纯', '时间', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('单依纯', '期待', 5);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('单依纯', '永远', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('单依纯', '牛班', 15);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('单依纯', '阳光', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('告五人', '不在意', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('告五人', '呜呜', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('告五人', '宇宙', 11);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('告五人', '有趣', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('告五人', '爱人', 11);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('告五人', '相撞', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('告五人', '街口', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('告五人', '西多士', 24);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('告五人', '错过', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('告五人', '魔法', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('太一', 'ai', 15);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('太一', '世界', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('太一', '可怜', 5);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('太一', '呐呐', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('太一', '害怕', 5);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('太一', '拥抱', 5);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('太一', '星星', 11);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('太一', '没用', 5);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('太一', '难过', 5);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('太一', '飞走', 11);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('女王蜂', 'Avu', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('女王蜂', 'Black', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('女王蜂', 'FLAT', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('女王蜂', 'is', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('女王蜂', 'it', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('女王蜂', 'life', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('女王蜂', 'love', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('女王蜂', 'up', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('女王蜂', 'VIOLENCE', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('容祖儿', 'fly', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('容祖儿', 'me', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('容祖儿', '习惯', 5);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('容祖儿', '伤心', 5);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('容祖儿', '小小的', 17);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('容祖儿', '忘记', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('容祖儿', '我要', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('容祖儿', '玫瑰', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('容祖儿', '脂粉', 5);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('容祖儿', '脸上', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('小霞', 'SEDAR', 23);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('小霞', 'Sound', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('小霞', 'Sterling', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('小霞', 'Studio', 23);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('小霞', '一种', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('小霞', '思念', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('小霞', '留恋', 13);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('小霞', '美丽', 13);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('小霞', '耳边', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('小霞', '蠢货', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('康熙', 'can', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('康熙', 'feel', 14);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('康熙', 'go', 14);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('康熙', 'just', 18);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('康熙', 'like', 15);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('康熙', '太原', 29);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('康熙', '女孩', 14);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('康熙', '滴答', 25);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('康熙', '留在', 29);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('康熙', '落泪', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('张碧晨', 'is', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('张碧晨', '一身', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('张碧晨', '倾斜', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('张碧晨', '可惜', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('张碧晨', '回忆', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('张碧晨', '星屑', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('张碧晨', '清晨', 5);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('张碧晨', '温柔', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('张碧晨', '爱情', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('张碧晨', '生命', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('李小眼', '不开', 14);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('李小眼', '世界', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('李小眼', '人心', 5);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('李小眼', '外面', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('李小眼', '妈妈', 23);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('李小眼', '孩子', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('李小眼', '永远', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('李小眼', '济南', 13);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('李小眼', '济水', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('李小眼', '爸爸', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('梨冻紧', 'go', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('梨冻紧', 'hold', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('梨冻紧', 'on', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('梨冻紧', 'to', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('梨冻紧', 'Wherever', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('梨冻紧', 'you', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('梨冻紧', '一秒', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('梨冻紧', '思念', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('梨冻紧', '我怕', 17);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('梨冻紧', '留下', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('江意间', 'get', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('江意间', 'me', 28);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('江意间', 'now', 18);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('江意间', 'Savage', 18);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('江意间', 'Zu', 84);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('江意间', '一点点', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('江意间', '夜未央', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('江意间', '好多', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('江意间', '时间', 14);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('汪苏泷', 'go', 17);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('汪苏泷', 'Letting', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('汪苏泷', 'That', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('汪苏泷', '大雨', 13);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('汪苏泷', '想念', 23);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('汪苏泷', '永远', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('汪苏泷', '爱情', 13);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('汪苏泷', '爱过', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('汪苏泷', '终于', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('汪苏泷', '落下', 15);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('法老', 'drunk', 56);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('法老', 'got', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('法老', 'know', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('法老', 'no', 77);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('法老', 'way', 79);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('法老', 'we', 15);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('法老', 'you', 17);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('法老', '太阳', 15);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('法老', '帅哥', 14);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('法老', '酒精', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('海洋Bo', 'Music', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('海洋Bo', 'RJ', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('海洋Bo', '一点点', 14);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('海洋Bo', '世界', 11);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('海洋Bo', '也许', 13);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('海洋Bo', '凌晨', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('海洋Bo', '妈妈', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('海洋Bo', '时间', 11);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('海洋Bo', '海洋', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('海洋Bo', '美丽', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('澤野弘之', 'and', 21);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('澤野弘之', 'be', 21);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('澤野弘之', 'get', 19);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('澤野弘之', 'it', 20);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('澤野弘之', 'my', 30);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('澤野弘之', 'the', 25);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('澤野弘之', 'to', 39);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('澤野弘之', 'We', 25);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('澤野弘之', 'you', 36);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('王胜娚', 'Studio', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('王胜娚', '七月', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('王胜娚', '人间', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('王胜娚', '北京', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('王胜娚', '夏末', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('王胜娚', '小小', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('王胜娚', '很小', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('王胜娚', '时间', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('王胜娚', '有限公司', 11);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('王胜娚', '红尘', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('王贰浪', '之间', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('王贰浪', '假装', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('王贰浪', '冷静', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('王贰浪', '哭泣', 11);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('王贰浪', '回忆', 11);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('王贰浪', '天空', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('王贰浪', '快乐', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('王贰浪', '时光', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('王贰浪', '爱情', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('王贰浪', '音乐', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('盛宇D-SHINE', 'baby', 21);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('盛宇D-SHINE', 'dance', 47);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('盛宇D-SHINE', 'Lonely', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('盛宇D-SHINE', 'Production', 20);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('盛宇D-SHINE', 'the', 15);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('盛宇D-SHINE', 'your', 17);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('盛宇D-SHINE', 'Zeus', 20);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('盛宇D-SHINE', '孤独', 21);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('盛宇D-SHINE', '宝贝', 18);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('盛宇D-SHINE', '舞步', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('米津玄師', 'BEAUTIFUL', 21);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('米津玄師', 'STAR', 21);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('米津玄師', '一人', 4);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('米津玄師', '一度', 4);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('米津玄師', '出会', 5);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('米津玄師', '努力', 21);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('米津玄師', '未来', 24);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('米津玄師', '花火', 5);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('米津玄師', '言葉', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('米津玄師', '面影', 4);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('花玲', 'chi', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('花玲', 'Chicken', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('花玲', 'pi', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('花玲', 'Pizza', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('花玲', 'Safari', 11);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('花玲', 'wu', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('花玲', '丽莎', 11);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('花玲', '天空', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('花玲', '舰长', 14);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('花玲', '走开', 13);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('蔡健雅', 'go', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('蔡健雅', '一种', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('蔡健雅', '学会', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('蔡健雅', '明白', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('蔡健雅', '有过', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('蔡健雅', '爱得', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('蔡健雅', '进化', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('蔡健雅', '迷了路', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('蔡健雅', '迷路', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('蔡健雅', '迷雾', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('薛之谦', '一场', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('薛之谦', '分开', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('薛之谦', '快乐', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('薛之谦', '慢慢', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('薛之谦', '明知', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('薛之谦', '演出', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('薛之谦', '离开', 11);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('薛之谦', '这是', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('薛之谦', '难过', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('薛之谦', '靠近', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('赵雷', '南方', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('赵雷', '姑娘', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('赵雷', '成都', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('赵雷', '抱抱', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('赵雷', '月亮', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('赵雷', '理想', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('赵雷', '画上', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('赵雷', '简单', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('赵雷', '街头', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('赵雷', '鼓楼', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('辛巴', 'better', 28);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('辛巴', 'Eh', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('辛巴', 'me', 28);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('辛巴', 'say', 19);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('辛巴', 'than', 27);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('辛巴', 'the', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('辛巴', 'you', 11);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('辛巴', '云朵', 11);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('辛巴', '讨论', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('辛巴', '远方', 13);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('那奇沃夫', 'baby', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('那奇沃夫', 'check', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('那奇沃夫', 'it', 27);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('那奇沃夫', 'like', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('那奇沃夫', 'me', 17);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('那奇沃夫', 'my', 27);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('那奇沃夫', 'no', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('那奇沃夫', 'on', 15);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('那奇沃夫', 'the', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('那奇沃夫', 'you', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('郑润泽', '不停', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('郑润泽', '习惯', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('郑润泽', '从前', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('郑润泽', '回到', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('郑润泽', '回忆', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('郑润泽', '寂寞', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('郑润泽', '就让', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('郑润泽', '思念', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('郑润泽', '落下', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('郑润泽', '送给', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('郭顶', 'it', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('郭顶', 'me', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('郭顶', 'to', 11);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('郭顶', 'we', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('郭顶', 'you', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('郭顶', '太久', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('郭顶', '时间', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('郭顶', '温柔', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('郭顶', '相遇', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('郭顶', '透过', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('金玟岐', 'Beijing', 11);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('金玟岐', 'Studio', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('金玟岐', '幸福', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('金玟岐', '想着', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('金玟岐', '拥有', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('金玟岐', '时间', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('金玟岐', '留下', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('金玟岐', '祝福', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('金玟岐', '腻味', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('金玟岐', '阿花', 9);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('队长', 'can', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('队长', 'go', 45);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('队长', 'know', 13);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('队长', 'let', 26);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('队长', 'NUNA', 15);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('队长', 'wanna', 13);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('队长', 'you', 27);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('队长', '你好', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('队长', '回来', 19);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('队长', '离开', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('陈近南', 'are', 31);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('陈近南', 'Baby', 27);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('陈近南', 'in', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('陈近南', 'light', 19);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('陈近南', 'relax', 32);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('陈近南', 'shiny', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('陈近南', 'So', 19);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('陈近南', 'the', 29);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('陈近南', 'you', 32);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('陶喆', 'Baby', 47);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('陶喆', 'Burbidge', 14);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('陶喆', 'Melody', 11);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('陶喆', 'Oh', 21);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('陶喆', 'Studios', 28);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('陶喆', '天天', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('陶喆', '女孩', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('陶喆', '明白', 16);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('陶喆', '永远', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('陶喆', '流沙', 10);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('马思唯', 'can', 19);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('马思唯', 'don', 22);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('马思唯', 'me', 19);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('马思唯', 'my', 22);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('马思唯', 'one', 23);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('马思唯', 'pull', 19);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('马思唯', 'She', 34);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('马思唯', 'to', 21);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('马思唯', 'up', 35);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('马思唯', 'you', 70);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('黄丽玲', 'Chow', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('黄丽玲', 'Sepnio', 7);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('黄丽玲', '万岁', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('黄丽玲', '多久', 12);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('黄丽玲', '寂寞', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('黄丽玲', '崩溃', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('黄丽玲', '幸福', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('黄丽玲', '悲伤', 8);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('黄丽玲', '爱情', 6);
INSERT INTO `singerWordAll` (`sename`, `word`, `num`) VALUES ('黄丽玲', '记得', 15);
