# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\pylearn\C15_BubbleSort\MainWidget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.resize(1077, 932)
        self.centralwidget = QtWidgets.QWidget(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tbTitle = QtWidgets.QToolButton(self.centralwidget)
        self.tbTitle.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbTitle.sizePolicy().hasHeightForWidth())
        self.tbTitle.setSizePolicy(sizePolicy)
        self.tbTitle.setMinimumSize(QtCore.QSize(700, 80))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(16)
        self.tbTitle.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/img/globe.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tbTitle.setIcon(icon)
        self.tbTitle.setIconSize(QtCore.QSize(64, 64))
        self.tbTitle.setCheckable(True)
        self.tbTitle.setChecked(True)
        self.tbTitle.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbTitle.setObjectName("tbTitle")
        self.verticalLayout_3.addWidget(self.tbTitle)
        self.verticalLayoutCountries = QtWidgets.QVBoxLayout()
        self.verticalLayoutCountries.setSpacing(2)
        self.verticalLayoutCountries.setObjectName("verticalLayoutCountries")
        self.verticalLayout_3.addLayout(self.verticalLayoutCountries)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pbStart = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbStart.sizePolicy().hasHeightForWidth())
        self.pbStart.setSizePolicy(sizePolicy)
        self.pbStart.setMinimumSize(QtCore.QSize(0, 120))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(16)
        self.pbStart.setFont(font)
        self.pbStart.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Images/img/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pbStart.setIcon(icon1)
        self.pbStart.setIconSize(QtCore.QSize(64, 64))
        self.pbStart.setObjectName("pbStart")
        self.verticalLayout.addWidget(self.pbStart)
        self.pbStop = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbStop.sizePolicy().hasHeightForWidth())
        self.pbStop.setSizePolicy(sizePolicy)
        self.pbStop.setMinimumSize(QtCore.QSize(0, 120))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(16)
        self.pbStop.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Images/img/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pbStop.setIcon(icon2)
        self.pbStop.setIconSize(QtCore.QSize(64, 64))
        self.pbStop.setObjectName("pbStop")
        self.verticalLayout.addWidget(self.pbStop)
        self.pbShuffle = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbShuffle.sizePolicy().hasHeightForWidth())
        self.pbShuffle.setSizePolicy(sizePolicy)
        self.pbShuffle.setMinimumSize(QtCore.QSize(0, 120))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(16)
        self.pbShuffle.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Images/img/poker.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pbShuffle.setIcon(icon3)
        self.pbShuffle.setIconSize(QtCore.QSize(64, 64))
        self.pbShuffle.setObjectName("pbShuffle")
        self.verticalLayout.addWidget(self.pbShuffle)
        self.pbAbout = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbAbout.sizePolicy().hasHeightForWidth())
        self.pbAbout.setSizePolicy(sizePolicy)
        self.pbAbout.setMinimumSize(QtCore.QSize(0, 120))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(16)
        self.pbAbout.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Images/img/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pbAbout.setIcon(icon4)
        self.pbAbout.setIconSize(QtCore.QSize(64, 64))
        self.pbAbout.setObjectName("pbAbout")
        self.verticalLayout.addWidget(self.pbAbout)
        self.pbExit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbExit.sizePolicy().hasHeightForWidth())
        self.pbExit.setSizePolicy(sizePolicy)
        self.pbExit.setMinimumSize(QtCore.QSize(0, 120))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(16)
        self.pbExit.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Images/img/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pbExit.setIcon(icon5)
        self.pbExit.setIconSize(QtCore.QSize(64, 64))
        self.pbExit.setObjectName("pbExit")
        self.verticalLayout.addWidget(self.pbExit)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        MainWidget.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWidget)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        _translate = QtCore.QCoreApplication.translate
        MainWidget.setWindowTitle(_translate("MainWidget", "Bubble Sort Demo..."))
        self.tbTitle.setText(_translate("MainWidget", "       GDP OF MAIN INDUSTRIAL COUNTRIES\n"
"                               (IN BILLIONS)"))
        self.pbStart.setText(_translate("MainWidget", "    START  "))
        self.pbStop.setText(_translate("MainWidget", "   STOP      "))
        self.pbShuffle.setText(_translate("MainWidget", "    SHUFFLE"))
        self.pbAbout.setText(_translate("MainWidget", "    ABOUT    "))
        self.pbExit.setText(_translate("MainWidget", "      EXIT       "))

import Images_rc
