"""
Draw mandelbrot set with matplotlib.
Matrix generated by Pure Python code.
chenbo@cqu.edu.cn,   Dec 2018.

Usage:
    key-up, key-down:  switch color map
"""



from matplotlib import pyplot as plt
from matplotlib import cm
import numpy as np

def getEscapeTime(c):
    "计算参数c的逃逸时间，该逃逸速度将用作点的颜色"
    z = 0
    for i in range(100):
        if abs(z) > 2:
            return i
        z = z*z + c
    return i

def computeMandelbrot(xCenter,yCenter,semiWidth,N):
    xFrom,xTo,yFrom,yTo = xCenter-semiWidth,xCenter+semiWidth,\
                          yCenter-semiWidth,yCenter+semiWidth
    y,x = np.ogrid[yFrom:yTo:N*1j,xFrom:xTo:N*1j]
    c = x + y*1j
    print("c.shape:",c.shape,"x.shape:",x.shape,"y.shape:",y.shape)
    return np.frompyfunc(getEscapeTime,1,1)(c).astype(np.float)

def drawMandelbrot(ax,xCenter,yCenter,semiWidth,N,cmap):
    "(xCenter,yCenter)-中心点，semiWidth-矩形半宽，N*N像素."
    ax.set_axis_off()
    ds = computeMandelbrot(xCenter,yCenter,semiWidth,N)
    ax.imshow(ds,cmap=cmap)

def refresh():
    c = cm.get_cmap(para.cmaps[para.idxColorMap%len(para.cmaps)])
    drawMandelbrot(para.ax0, para.x, para.y,
                   semiWidth=0.2, N=600,cmap=c)
    drawMandelbrot(para.ax1, para.x, para.y,
                   semiWidth=0.2 ** 3, N=600,cmap=c)
    para.fig.canvas.draw()

def on_key_release(event):
    if event.key == 'up':
        para.idxColorMap+=1
    elif event.key == 'down':
        para.idxColorMap-=1
    else:
        return
    refresh()

class Para:
    pass

para = Para()
para.x, para.y = 0.27322626, 0.595153338
para.idxColorMap = 0
para.cmaps = ['rainbow', 'jet', 'nipy_spectral', 'gist_ncar','flag',
              'prism', 'ocean', 'gist_earth', 'terrain', 'gist_stern',
              'gnuplot', 'gnuplot2', 'CMRmap', 'cubehelix', 'brg',
              'gist_rainbow']
para.fig = plt.figure(figsize=(12,6),dpi=100)
para.fig.canvas.mpl_connect('key_release_event',on_key_release)
plt.subplots_adjust(0,0,1,1,0.0,0)
para.ax0 = plt.subplot(121)
para.ax1 = plt.subplot(122)
refresh()
plt.show()
